os: linux
language: python
services: docker

before_script:
  - git clone --depth=1 https://$GIT_TOKEN@github.com/xmjiao/ci-util.git

script:
  - export CHILDREN=CHILDREN_${TRAVIS_BRANCH} && ./ci-util/trigger-via-api.sh ${!CHILDREN}
