os: linux
language: python
services: docker

env: CHILDREN=CHILDREN_${TRAVIS_BRANCH}

before_script:
  - git clone --depth=1 https://$GIT_TOKEN@github.com/xmjiao/ci-util.git

script:
  - ./ci-util/trigger-via-api.sh ${!CHILDREN}
